# Change these first
owner: girolamodaschio # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Presidenza del Consiglio dei Ministri - OpenCup
    url: https://www.opencup.gov.it/
  - name: Ministero Dei Trasporti - Portale OpenData
    url: https://dati.mit.gov.it/catalog/dataset/scp
  - name: Ragioneria Generale dello Stato - OpenBDAP
    url: https://openbdap.rgs.mef.gov.it/
  - name: ItaliaDomani - Catalogo OpenData
    url: https://www.italiadomani.gov.it
  - name: ANAC - OpenData
    url: https://dati.anticorruzione.it/opendata
  - name: Portale Datibenecomune
    url: https://www.datibenecomune.it
