# Change these first
owner: girolamodaschio # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Presidenza del Consiglio dei Ministri - OpenCup
    url: https://www.opencup.gov.it/
  - name: Ministero Dei Trasporti - Portale OpenData
    url: https://dati.mit.gov.it/catalog/dataset/scp
  - name: Ragioneria Generale dello Stato - OpenBDAP
    url: https://openbdap.rgs.mef.gov.it/
  - name: ANAC - OpenData
    url: https://dati.anticorruzione.it/opendata
  - name: Portale Dati Bene Comune
    url: https://www.datibenecomune.it





skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"


i18n:
  footer: This page is [open source]($REPO)
